# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{google_visualr}
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Winston Teo"]
  s.date = %q{2010-05-04}
  s.description = %q{Write Ruby code. Generate Javascript. Display a Google Visualization.}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/google_visualr.rb",
     "lib/google_visualr/annotated_time_line.rb",
     "lib/google_visualr/area_chart.rb",
     "lib/google_visualr/bar_chart.rb",
     "lib/google_visualr/base_chart.rb",
     "lib/google_visualr/column_chart.rb",
     "lib/google_visualr/formatters.rb",
     "lib/google_visualr/gauge.rb",
     "lib/google_visualr/image_spark_line.rb",
     "lib/google_visualr/intensity_map.rb",
     "lib/google_visualr/line_chart.rb",
     "lib/google_visualr/map.rb",
     "lib/google_visualr/motion_chart.rb",
     "lib/google_visualr/org_chart.rb",
     "lib/google_visualr/pie_chart.rb",
     "lib/google_visualr/scatter_chart.rb",
     "lib/google_visualr/table.rb"
  ]
  s.homepage = %q{http://github.com/winston/google_visualr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Ruby Library for the Google Visualization API}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

